name: attendance

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  workflow_call:
    secrets:
      KURO_TOKEN:
        required: true
      BARK_TOKEN:
        required: false
    inputs:
      repository:
        description: 'The repository to run the workflow on'
        default: 'Magic-Xin/Kuro-autosignin'
        required: false
        type: string

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Edit config files
        env:
          KURO_TOKEN: ${{ secrets.KURO_TOKEN }}
          BARK_TOKEN: ${{ secrets.BARK_TOKEN }}
        run: |
          set -euo pipefail

          python edit_config.py --kuro-token "${KURO_TOKEN}" --bark-token "${BARK_TOKEN}"

      - name: Run sign-in
        env:
          KuroBBS_log_level: INFO
        run: |
          python main.py
